### Standartization

In this example, we do the standartization of the data using a z-traformation

$$
    z_i = \frac{x_i - \bar{x}}{sd(x)}
$$

for each feature (column of the data matrix) separately. See also: http://scikit-learn.org/stable/modules/preprocessing.html

In [7]:
import numpy as np
X_train = np.array([[1., -1., 2.],[2., 0., 0.], [0,1,-1], [1,2,3]])

import pandas as pd
pd.DataFrame(X_train) #Just for nice plotting

0    1    2
0  1.0 -1.0  2.0
1  2.0  0.0  0.0
2  0.0  1.0 -1.0
3  1.0  2.0  3.0

In [9]:
np.mean(X_train, axis=0) #The mean values for each row (axis = 0)

array([1. , 0.5, 1. ])

In [15]:
X_scaled = (X_train - np.mean(X_train, axis=0)) / (np.std(X_train, axis=0) + 1e-14) #1e-14 numerical trick to prevent division by zero
pd.DataFrame(X_scaled) #Just for nice plotting

0         1         2
0  0.000000 -1.341641  0.632456
1  1.414214 -0.447214 -0.632456
2 -1.414214  0.447214 -1.264911
3  0.000000  1.341641  1.264911

In [18]:
np.mean(X_scaled, axis=0), np.std(X_scaled, axis=0)

(array([0., 0., 0.]), array([1., 1., 1.]))

In [19]:
## Using sklearn
from sklearn import preprocessing
preprocessing.scale(X_train)

array([[ 0.        , -1.34164079,  0.63245553],
       [ 1.41421356, -0.4472136 , -0.63245553],
       [-1.41421356,  0.4472136 , -1.26491106],
       [ 0.        ,  1.34164079,  1.26491106]])