## A Collection of usefull bit&pices for numpy [Work in progress]
For someone comming from java, R

In [1]:
import numpy as np

In [2]:
d = np.asarray((0,1.0,-1.0))
d.dtype, d.shape

(dtype('float64'), (3,))

#### Sorting, max, mean
Note the d[::-1] reverses the order

In [3]:
# Does an inplace sorting
dd = np.copy(d) #Cloning
dd.sort() #Note that the sorting is done in place
dd, dd.max(), dd.min(), dd.mean(), dd.var(), dd[::-1]

(array([-1.,  0.,  1.]),
 1.0,
 -1.0,
 0.0,
 0.66666666666666663,
 array([ 1.,  0., -1.]))

#### Getting the sorted indices

In [4]:
print(d.argsort(), d.argmax())
m = np.asarray(((2,3,4),(5,4,5)))
print(m.shape, m.max())
m.argmax(),#m[m.argmax()] does not work

(array([2, 0, 1]), 1)
((2, 3), 5)


(3,)